const paths = Object.assign({},
    { p1q1: "https://drive.google.com/file/d/1n5dD1zhhZUrRoZJXmAvj4a4YjSDmv85v/preview"},
    { p1s1: "https://drive.google.com/file/d/17VOeYgmMPurViSuD4GKh33KM_iOxZxHy/preview"},
    { p1q2: "https://drive.google.com/file/d/1rfkh5CerPJVKMW3PdkO0AkBPJHyNU06F/preview"},
    { p1s2: "https://drive.google.com/file/d/1S3aKDxx-GbCg9TmzRRAQVDMJUoiRHyI3/preview"},
    { p1q3: "https://drive.google.com/file/d/1Z803Kq41c2sEJ_YWCwzf33IgIU-idfuM/preview"},
    { p1s3: "https://drive.google.com/file/d/1BKNva5vj9eM8zpzbd6dGICS-Iw-MjOTT/preview"},
    { p1q4: "https://drive.google.com/file/d/1hbZpjEoUus1-cuQBrW7htMuAw_pKqCxW/preview"},
    { p1s4: "https://drive.google.com/file/d/1Icf2CeKFx-4mGQVZOpFDWpl2xQhyLeYN/preview"},
    { p1q5: "https://drive.google.com/file/d/1ky7_Hc266HrZeqVmZVzVr-EfXphtjrnT/preview"},
    { p1s5: "https://drive.google.com/file/d/1CJ9W63FeK64mPg0SuHzqFr3cx0tXOCvD/preview"},
    { p1q6: "https://drive.google.com/file/d/1ISr7DWOlJgpqBRtt1eisPfaqn_FwK3zk/preview"},
    { p1s6: "https://drive.google.com/file/d/1jPo_0t7zBikKZV1-C4Z-gPmvf8a_0nPA/preview"},
    { p1q7: "https://drive.google.com/file/d/1oUwGicvcvUbmKkuwj7KxdvwAIIoqrmcX/preview"},
    { p1s7: "https://drive.google.com/file/d/1v6iRbe0aTxOD5V1FZkgiC5y1B8Hkb6ah/preview"},
    { p1q8: "https://drive.google.com/file/d/1qjxN7TiY--l4R-i76B-_BsRh53Pwcc0z/preview"},
    { p1s8: "https://drive.google.com/file/d/1KF_LdeACe_5uIshhPWVM_1s7X_PT1F0g/preview"},
    { p3q1: "questions1"},
    { p3s1: "solutions1"},
    { p3q2: "questions2"},
    { p3s2: "solutions2"},
    { p3q3: "questions3"},
    { p3s3: "solutions3"},
    { p3q4: "questions4"},
    { p3s4: "solutions4"},
    { p3q5: "questions5"},
    { p3s5: "solutions5"},
    { p3q6: "questions6"},
    { p3s6: "solutions6"},
);

export {paths}