import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Table, Header} from "semantic-ui-react";
import topics from "../utils/topics.json"
import {useRouter} from "next/router";


export default function Home() {

    const router = useRouter()

    const handleClick = (id) => {
        router.push({
            pathname: `/file-display`,
            query: {
                id: id
            }
            }
        )
    }
    return (
        <>
            <div style={{marginTop: "20px", justifyContent: "space-evenly"}}>
                <Head>
                    <title>CS Wizard</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                {/*<Header as="h1" style={{backgroundColor: "blue", textAlign: "center"}}>CIE A Level CS</Header>*/}

                <Header as="h2" style={{backgroundColor: "grey", textAlign: "center"}}>Paper 1</Header>
                <Table celled style={{margin: "auto"}}>
                    <Table.Header>
                        <Table.Row>
                            <Table.HeaderCell className={styles.gridHeaders}>Topic</Table.HeaderCell>
                            <Table.HeaderCell className={styles.gridHeaders}>Exam Questions</Table.HeaderCell>
                            <Table.HeaderCell className={styles.gridHeaders}>Solutions</Table.HeaderCell>
                        </Table.Row>
                    </Table.Header>
                    <Table.Body>
                        {Array.from({length: 8}, (_, i) => (
                            <Table.Row key={i}>
                                <Table.Cell style={{padding: 10}}>{topics.paper1[i]}</Table.Cell>
                                <Table.Cell className={styles.questionsAndSolutions} onClick={()=>handleClick(`p1questions${i+1}`)}>Questions</Table.Cell>
                                <Table.Cell className={styles.questionsAndSolutions}
                                            onClick={() => handleClick(`p1solutions${i + 1}`)}>Solutions</Table.Cell>
                            </Table.Row>
                        ))}
                    </Table.Body>
                </Table>

                <Header as="h2" style={{backgroundColor: "grey", textAlign: "center"}}>Paper 3</Header>
                <Table celled style={{margin: "auto"}}>
                    <Table.Header>
                        <Table.Row>
                            <Table.HeaderCell className={styles.gridHeaders}>Topic</Table.HeaderCell>
                            <Table.HeaderCell className={styles.gridHeaders}>Exam Questions</Table.HeaderCell>
                            <Table.HeaderCell className={styles.gridHeaders}>Solutions</Table.HeaderCell>
                        </Table.Row>
                    </Table.Header>
                    <Table.Body>
                        {Array.from({length: 6}, (_, i) => (
                            <Table.Row key={i}>
                                <Table.Cell style={{padding: 10}}>{topics.paper3[i]}</Table.Cell>
                                <Table.Cell className={styles.questionsAndSolutions}
                                            onClick={() => handleClick(`p3questions${i + 1}`)}>Questions</Table.Cell>
                                <Table.Cell className={styles.questionsAndSolutions}
                                            onClick={() => handleClick(`p3solutions${i + 1}`)}>Solutions</Table.Cell>
                            </Table.Row>
                        ))}
                    </Table.Body>
                </Table>
            </div>
            <div style={{textAlign: "center", marginTop: 20}}>
                <p>By Yoel Gal, aka Bernard</p>
                <p>Check me out: <a className={styles.link} href="https://github.com/yoelgal">Github</a></p>
                <p className={styles.footerSmall}>Copyright © Yoel Gal</p>
                <p className={styles.footerSmall}>Disclaimer: All questions and solutions shown are property of CIE</p>
            </div>
        </>
    )
}
